# Generated by Django 4.1.2 on 2022-11-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kursun adını yazınız.', max_length=200, verbose_name='Kurs adı: ')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='courses/default-placeholder.png', upload_to='courses/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
